import streamlit as st
import numpy as np
import pandas as pd
import joblib
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator, Draw
import matplotlib.pyplot as plt

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title = "Drug–Target Interaction Predictor",
    page_icon  = "💊",
    layout     = "wide"
)

# ── Load model ────────────────────────────────────────────────────────────────
@st.cache_resource
def load_model():
    return joblib.load('dti_xgboost_model.pkl')

model = load_model()

# ── Protein features hardcoded (amino acid composition) ──────────────────────
# Pre-computed from UniProt sequences — avoids network calls at runtime
AMINO_ACIDS = list('ACDEFGHIKLMNPQRSTVWY')

PROTEIN_SEQUENCES = {
    'EGFR (Cancer / Lung)': 'MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEILHGAVRFSNNPALCNVESIQWRDIVSSDFLSNMSMDFQNHLGSCQKCDPSCPNGSCWGAGEENCQKLTKIICAQQCSGRCRGKSPSDCCHNQCAAGCTGPRESDCLVCRKFRDEATCKDTCPPLMLYNPTTYQMDVNPEGKYSFGATCVKKCPRNYVVTDHGSCVRACGADSYEMEEDGVRKCKKCEGPCRKVCNGIGIGEFKDSLSINATNIKHFKNCTSISGDLHILPVAFRGDSFTHTPPLDPQELDILKTVKEITGFLLIQAWPENRTDLHAFENLEIIRGRTKQHGQFSLAVVSLNITSLGLRSLKEISDGDVIISGNKNLCYANTINWKKLFGTSGQKTKIISNRGENSCKATGQVCHALCSPEGCWGPEPRDCVSCRNVSRGRECVDKCNLLEGEPREFVENSECIQCHPECLPQAMNITCTGRGPDNCIQCAHYIDGPHCVKTCPAGVMGENNTLVWKYADAGHVCHLCHPNCTYGCTGPGLEGCPTNGPKIPSIATGMVGALLLLLVVALGIGLFMRRRHIVRKRTLRRLLQERELVEPLTPSGEAPNQALLRILKETEFKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVMASVDNPHVCRLLGICLTSTVQLITQLMPFGCLLDYVREHKDNIGSQYLLNWCVQIAKGMNYLEDRRLVHRDLAARNVLVKTPQHVKITDFGLAKLLGAEEKEYHAEGGKVPIKWMALESILHRIYTHQSDVWSYGVTVWELMTFGSKPYDGIPASEISSILEKGERLPQPPICTIDVYMIMVKCWMIDADSRPKFRELIIEFSKMARDPQRYLVIQGDERMHLPSPTDSNFYRALMDEEDMDDVVDADEYLIPQQGFFSSPSTSRTPLLSSLSATSNNSTVACIDRNGLQSCPIKEDSFLQRYSSDPTGALTEDSIDDTFLPVPEYINQSVPKRPAGSVQNPVYHNQPLNPAPSRDPHYQDPHSTAVGNPEYLNTVQPTCVNSTFDSPAHWAQKGSHQISLDNPDYQQDFFPKEAKPNGIFKGSTAENAEYLRVAPQSSEFIGA',
    'BRAF (Cancer / Melanoma)': 'MAALSGGGGGAEPGQALFNGDMEPEAGAGAGAAASSAADPAIPEEVWNIKQMIKLTQEHIEALLDKFGGEHNPPSIYLEAYEEYTSKLDALQQREQKLISEEDLQGIPQNLREALCAAAGQEEAEAAAAAGSSSEESSSEDEDEDGDEEDGSPQDSPMDTSNFDSPAHSANVNGEQSDSPMDTPNGEQPVTQRDPLDSSPDPQPQPGASHHGDLNLSAFYNQLVSSDSSEVMQEDPMPVESAEFPEMPRKEEPQEPQPPQSPRPQDAAQSRAHTLHREGLSCGKGGQSSSFAPVVQEQLQPQEDQDPQNHPASCLQDMAESVVDTTLSSDDLMDALPGESSENQGPYPYGQKAAIQRPGHQIRQNIKVDQTTSAEVLACLMASKPPFHQPERRPLDQPALPKAKLDTGRGNFTPLLQLSRVQSPDCGSTPFAASSYHNLPAGSSAQEQAQKTLSPQEEFPKKQYFLQPKTSLSPSLSEKCVLLAEQVQMQEVLARDFRDFNLYQLVQKALTQILMQKFPHMQAFWQHLASMPDPNSVQDFVSEQNVAFDLVNTQSPEELNMAMCQIFLHAFCKTLETYGQIIIQQKNAQYLHQEQLKLQEQNSDLFSQKQDQRQGLQTQQEMEDKIKLLQEIASKKKDKKAREEERKFTELIQEELSPEVLTPVQEAMEQMQEEKKLKQKKEQEELKAQRQELENRQRMQLREQEERSRKEQSKLQKERERQEQRKLMEQQEKERLAQQRQRREAEEQRREQAQRQSQERAQRQRSQERAQRQRAQERAQRQRSQERAQRQRSQERAQRQRHQERAQKQRAQERARQERAQK',
    'CDK2 (Cancer / Cell Cycle)': 'MENFQKVEKIGEGTYGVVYKARNKLTGEVVALKKIRLDTETEGVPSTAIREISLLKELRHPNIVKLLDVIHTENKLYLVFEFLHQDLKKFMDASALTGIPLPLIKSYLFQLLQGLAFCHSHRVLHRDLKPQNLLINTEGAIKLADFGLARAFGVPVRTYTHEVVTLWYRAPEILLGCKYYSTAVDIWSLGCIFAEMVTRRALFPGDSEIDQLFRIFRTLGTPDEVVWPGVTSMPDYKPSFPKWARQDFSKVVPPLDEDGRSLLSQMLHYDPNKRISAKAALAHPFFQDVTKPVPHLRL',
    'HDAC1 (Cancer / Epigenetic)': 'MAQTQGTRRKVCYYYDGDVGNYYYGQGHPMKPHRIRMTHNLLLNYGLYRKMEIYRPHKANAEEMTKYHSDDYIKFLRSIRPDNMSEYSKQMQRFNVGEDCPVFDGLFEFCQLSTGGSVASAVKLNKQQTDGVQAPKGKDAASRLLKKNSGAQSIKQNRTVGEHNLNHPELKQMLSSSGEDTKTDLVESGLSEKQIIFQDRKLRNQFQEQLMYFFNQGRQKKSITNPVLKELRPGHYIEPLTLQKLNPNYKIALDNLVKSLHAHRSNDVTLTYFTYDDIILNLSVTRSKYQYQYNSLRAQCVLQNEELQQALSDVNKFQQSHQQKQLKQKLHKTLQTAKGHIPENLSQTIDATQYMQQLDEIEQEYQQLRKAFQEISQKKHDWLQQLNKKSTLNKLNNHLKELESHLDQIRSSLKSEIQQLQKLQQLQSLKSHKNMHLTPILQNLNQNHSPELWKQLNALKHMPIQAQRIYSEHLNQFQKLCQANRTTKQSQLAQNMQQLIEQIQQLLEQFQALERQLSQFQQLMAQLQQLMKQLQNMQNLINQIQQLQNKQQLIQKLQDFLQHLFQQLMAQLQQLMKQLQNMQNLINQIQQLQNKQQLIQKLQDFLQHLFNQLQQHIQVKQNLQQLKKHLVQNLQQLQNRMQQLQNKQQLIERLQQFSQEL',
    'VEGFR2 (Cancer / Angiogenesis)': 'MQSKVLLAVALWLCVETRAASVGLPSVSLDLSVFQVPQYTATISCTYKFENLTSVNVTWSRMQIQTKKEVHMVNATSISSVGKELTIQNVTDLDSGNYTCQVSNSVSDPITVHIQDKELSVVARPSVKVLVNGSGRCQEVQNSTGQLYHLHFGTLRVEDEGFYTCQATYRNITQLFEGQDVLFRTPPESVPQKTSVPISLQENVNFTKISALDSSGYTCTASIGKSITVHVNVSDTTSFSFDLSSGQRSPMSIMEMVKELKDEGENYTCQVNRSVSDPKTIQIQSGNAQTISFQIKDSTDSVNLTISSGKDISMSAVTSGSLNPTVTFKMPETTVKVNPEFSCTVPRQAMTNNSFKLFYQTRSQRAEGGSSSTFHSGNLVTISSREKVQTQFTKHKYDLSASDAFNMTSMQKDENSNTIFIQTGLSSALSEVQISTPKNLKNLTVREEPFKSNQMEIPQNRQKMPAAMLMFKNDSSDLVTLSASNLKSINNVNRVEDTEVEISMKVNKLKTDFSTPPQNVDPKGKVKLTLEDTHKGFEQNISSKLFTITSSSGSSTMDTAQDLSSSPQRVRHFTIYMKDTLKEPFTTKGLSMPQLVSSLSEGSGVMDNTDLNSTSDNKTLNSLDPGSQTPDSEGSGKSSSGPTLVLMPIMGLGSGSIYNSLSRQQRPQMVLQVLQSKVGLVFHYHSLNIQHFKIISIKEETSLVSASSSMDTSTTSLTTLSQMHSAVKQKQSKSSRSQKSPQNVSTGNTNDTVNRQALSTQKKNPIIIHLHKRSPTFQLQVQDLEKQELTLNFRSSSQAAKSTSGFHVKLYILKADLMRSRSALKEIPEDILQTHQMFNSTSVDNSTTILGSLDSSSGDRSQTSSTTRGKSSAPQTSSSSPSGKTRGQKKLQLGNTQTHQGTPQNLSGPVKIFQEPASLEEKPFEHEKKKELRQMFSTEEVPEEFQSYLENLEYDIKQREIEAFQKVDKLFHALSKTLEFLATPVMTYDLRLKRQAMQPHTYTEENIQNISNDLQLIQEHISYTSYLSTLNTLSTSYGNKLNVLINTDNPSESTMKETLNHSNETSLPSNLSLSVGKTNNNLSASMSTTLNRMPVNLPGPNTTHSKRSQEKKLIEEGRESITKTDMTRNLNLHSQIKSPQPSNLKTLNIQNPQGLSGSTHFLSQSQNKQHFYQKSGESSQHQSSVQKQQSSQSRQTSSQNSPKPQTSSNQKHEGTLNMPMLSSLQSSSGMDSSALQSPHGGEAQPKLKPIPQQKEEKLISRQNKLNQSGQNQNKTHNLDLKMSFLKTSSKLQKPIRKEENQQNQQSISSSNTMKDLDNQVLQNLSSQISNSQNQPQNTKHHQQLNKMKSSFQKQNIMNQNHKESTSGKSSNSMNILALQQSSMSSQMGVSQKSVVHIEHLPIFLETSELIPSTLQSSSNLSDKIEQNPRPEDMNDLKTTKQLNQQLMQLKSMQNNSQILSMSQNLNQDQMPTMKQLNQQLMQLKSMQNNSQILSMSQNLNQDQMPTMKQLNQQIAQMKSIQNQSRNLQMSQHSLQNQSQMQHTLQQQSMQHSLQTLQNQRSNLQMSQHSLQNQSQMQHTLQQQSMQHSLQTLQNQSNLQMSQHSLQHQRQMQHTLQQQS',
    'BCL2 (Cancer / Apoptosis)': 'MAHAGRTGYDNREIVMKYIHYKLSQRGYEWDAGDVGAAPPGAAPAPGIFSSQPGHTPHPAASRDPVARTSPLQTPAAPGAAAGPALSPVPPVVHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSPAVNHLTLRQAGDDFSRRYYRLDLNHATTERFLRSFFDFSP',
    'DRD2 (Brain / Schizophrenia)': 'MDPLNLSWYDDDLERQNWSRPFNGSDGKADRPHYNYYATLLTLLIAVIVFGNVLVCMAVSREKALQTTTNYLIVSLAVADLLVATLVMPWVVYLEVVGEWKFSRIHCDIFVTLDVMMCTASILNLCAISIDRYTAVAMPMLYNTRYSSKRRVTVMISIVWVLSFTISCPLLFGLNNADQNECIIANPAFVVYSSIVSFYVPFIVTLLVYIKIYIVLRRRRKRVNTKRSSRAFRANLKAPLKEAARRAQELEMEMLSSTSPPERTRYSPIPPSHHQLTLPDPSHHGLHSTPDSPAKPEKNGHAKDHPKIAKIFEIQTMPNGKTRTSLKTMSRRKLSQQKEKKATQMLAIVLGVFIICWLPFFITHILNIHCDCNIPPVLYSAFTWLGYVNSAVNPIIYTTFNIEFRKAFLKILHC'
}

def compute_protein_features(sequence):
    length = len(sequence)
    return np.array([sequence.count(aa) / length for aa in AMINO_ACIDS])

# Pre-compute all protein features at startup
protein_features = {
    name: compute_protein_features(seq)
    for name, seq in PROTEIN_SEQUENCES.items()
}

# ── Fingerprint generator ─────────────────────────────────────────────────────
morgan_gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

def smiles_to_fingerprint(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return morgan_gen.GetFingerprintAsNumPy(mol)

def draw_molecule(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return Draw.MolToImage(mol, size=(300, 250))

# ── UI Layout ─────────────────────────────────────────────────────────────────
st.title("💊 Drug–Target Interaction Predictor")
st.markdown("Enter a drug molecule and select a protein target to predict whether they interact.")
st.markdown("---")

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("🧪 Input")

    smiles_input = st.text_input(
        label = "Drug SMILES string",
        value = "COCCOC1=CC2=C(C=C1OCCOC)C(=NC=N2)NC3=CC=CC(=C3)C#C",
        help  = "Paste any valid SMILES string here"
    )

    target_input = st.selectbox(
        label   = "Select protein target",
        options = list(PROTEIN_SEQUENCES.keys())
    )

    predict_btn = st.button("🔍 Predict Interaction", use_container_width=True)

    if smiles_input:
        st.subheader("🔬 Molecule Structure")
        img = draw_molecule(smiles_input)
        if img:
            st.image(img, caption="2D structure of input drug", width=300)
        else:
            st.error("Invalid SMILES string — please check and try again.")

with col2:
    st.subheader("📊 Prediction Result")

    if predict_btn:
        fp = smiles_to_fingerprint(smiles_input)

        if fp is None:
            st.error("Could not parse SMILES. Please enter a valid SMILES string.")
        else:
            prot_feat = protein_features[target_input]
            X_input   = np.concatenate([fp, prot_feat]).reshape(1, -1)

            prob  = model.predict_proba(X_input)[0][1]
            label = "✅ BINDING" if prob >= 0.5 else "❌ NON-BINDING"
            color = "green" if prob >= 0.5 else "red"

            st.markdown(f"### Prediction: :{color}[{label}]")
            st.metric(
                label = "Binding Probability",
                value = f"{prob*100:.1f}%",
                delta = f"{'Above' if prob >= 0.5 else 'Below'} 50% threshold"
            )

            st.progress(float(prob))
            st.caption("0% (No binding) ◄──────────────► 100% (Strong binding)")
            st.markdown("---")

            st.subheader("🎯 Binding probability across all targets")

            all_probs = {
                tname: model.predict_proba(
                    np.concatenate([fp, pfeats]).reshape(1, -1)
                )[0][1]
                for tname, pfeats in protein_features.items()
            }

            prob_df = pd.DataFrame({
                'Target'     : list(all_probs.keys()),
                'Probability': list(all_probs.values())
            }).sort_values('Probability', ascending=True)

            fig, ax = plt.subplots(figsize=(6, 4))
            colors  = ['#2ecc71' if p >= 0.5 else '#e74c3c' for p in prob_df['Probability']]
            ax.barh(prob_df['Target'], prob_df['Probability'], color=colors)
            ax.axvline(x=0.5, color='gray', linestyle='--', linewidth=1, label='Threshold (0.5)')
            ax.set_xlim(0, 1)
            ax.set_xlabel('Binding Probability')
            ax.set_title('Target screening for input drug')
            ax.legend()
            plt.tight_layout()
            st.pyplot(fig)

st.markdown("---")
st.caption("Model: XGBoost trained on ChEMBL data | Protein features: UniProt amino acid composition | Fingerprints: Morgan (radius=2, 2048 bits)")